services:
  admin-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:3000"
    environment:
      - NEXT_PUBLIC_ADMIN_API_URL=http://192.168.11.13:4100
    restart: unless-stopped

  admin-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4100:4100"
    env_file:
      - ../../.env
    environment:
      - REDIS_STREAM_URL=redis://stream-redis:6379
    networks:
      - default
      - prism_stream_default
    restart: unless-stopped

networks:
  prism_stream_default:
    external: true
